/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Clases;

import javax.swing.JOptionPane;

/**
 *
 * @author Jemma
 */
public class Ventana extends javax.swing.JInternalFrame {
        
        int c=0;
        int c2=0;
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        optSuma = new javax.swing.JRadioButton();
        optResta = new javax.swing.JRadioButton();
        optMult = new javax.swing.JRadioButton();
        optDivision = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        lblresultado = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btnCalcular = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnSuma = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        btnMult = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setClosable(true);
        setTitle("Operaciones");

        jPanel1.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel1.setLayout(new java.awt.GridLayout(4, 1));

        buttonGroup1.add(optSuma);
        optSuma.setSelected(true);
        optSuma.setText("Suma");
        optSuma.setEnabled(false);
        optSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optSumaActionPerformed(evt);
            }
        });
        jPanel1.add(optSuma);

        buttonGroup1.add(optResta);
        optResta.setText("Resta");
        optResta.setEnabled(false);
        optResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optRestaActionPerformed(evt);
            }
        });
        optResta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                optRestaKeyTyped(evt);
            }
        });
        jPanel1.add(optResta);

        buttonGroup1.add(optMult);
        optMult.setText("Multiplicacion");
        optMult.setEnabled(false);
        jPanel1.add(optMult);

        buttonGroup1.add(optDivision);
        optDivision.setText("Divicion");
        optDivision.setEnabled(false);
        jPanel1.add(optDivision);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setLayout(new java.awt.GridLayout(4, 2));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel8);

        txt1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txt1.setForeground(new java.awt.Color(0, 0, 0));
        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });
        txt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt1KeyTyped(evt);
            }
        });
        jPanel2.add(txt1);

        txt2.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        txt2.setForeground(new java.awt.Color(0, 0, 0));
        txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt2ActionPerformed(evt);
            }
        });
        txt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt2KeyTyped(evt);
            }
        });
        jPanel2.add(txt2);

        jPanel9.setLayout(new java.awt.GridLayout(1, 1));

        lblresultado.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblresultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblresultado.setText("0.0");
        jPanel9.add(lblresultado);

        jPanel2.add(jPanel9);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setPreferredSize(new java.awt.Dimension(394, 20));
        jPanel3.setLayout(new java.awt.GridLayout(1, 1));

        jLabel2.setFont(new java.awt.Font("Shrikhand", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Operaciones Aritmeticas");
        jPanel3.add(jLabel2);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel4.setLayout(new java.awt.GridLayout(1, 4));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 133, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel7);

        btnCalcular.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(0, 0, 0));
        btnCalcular.setText("Calcular");
        btnCalcular.setEnabled(false);
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        btnCalcular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnCalcularKeyTyped(evt);
            }
        });
        jPanel4.add(btnCalcular);

        btnCerrar.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(0, 0, 0));
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel4.add(btnCerrar);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 133, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel6);

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel5.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel5.setLayout(new java.awt.GridLayout(4, 1));

        btnSuma.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 18)); // NOI18N
        btnSuma.setForeground(new java.awt.Color(0, 0, 0));
        btnSuma.setText("Suma");
        btnSuma.setEnabled(false);
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });
        jPanel5.add(btnSuma);

        btnResta.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 18)); // NOI18N
        btnResta.setForeground(new java.awt.Color(0, 0, 0));
        btnResta.setText("Resta");
        btnResta.setEnabled(false);
        btnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaActionPerformed(evt);
            }
        });
        jPanel5.add(btnResta);

        btnMult.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 18)); // NOI18N
        btnMult.setForeground(new java.awt.Color(0, 0, 0));
        btnMult.setText("Multi");
        btnMult.setEnabled(false);
        btnMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultActionPerformed(evt);
            }
        });
        jPanel5.add(btnMult);

        btnDivision.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 18)); // NOI18N
        btnDivision.setForeground(new java.awt.Color(0, 0, 0));
        btnDivision.setText("Division");
        btnDivision.setEnabled(false);
        btnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisionActionPerformed(evt);
            }
        });
        jPanel5.add(btnDivision);

        getContentPane().add(jPanel5, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void optRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optRestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optRestaActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.hide();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1ActionPerformed

    private void txt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt1KeyTyped
     
       int key = evt.getKeyChar();
       if ((key >=48 && key<=57) || key == 46){
           c++;
       }else{
           evt.consume();
       }
       if (c>0 && c2>0){
           btnSuma.setEnabled(true);
           btnResta.setEnabled(true);
           btnMult.setEnabled(true);
           btnDivision.setEnabled(true);
           optSuma.setEnabled(true);
           optResta.setEnabled(true);
           optMult.setEnabled(true);
           optDivision.setEnabled(true);
           btnCalcular.setEnabled(true);
       }else{
           btnSuma.setEnabled(false);
           btnResta.setEnabled(false);
           btnMult.setEnabled(false);
           btnDivision.setEnabled(false);
           optSuma.setEnabled(false);
           optResta.setEnabled(false);
           optMult.setEnabled(false);
           optDivision.setEnabled(false);
           btnCalcular.setEnabled(false);
           
       }
       if (key==8){
          c--;
       }
        
       // JOptionPane.showMessageDialog(null,evt.getKeyChar());        // TODO add your handling code here:
    }//GEN-LAST:event_txt1KeyTyped

    private void txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt2ActionPerformed

    private void txt2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt2KeyTyped
        
        int key = evt.getKeyChar();
        
       if ((key >=48 && key<=57) || key ==46){
           c2++;
       }else{
           evt.consume();
       }
       if (c>0 && c2>0){
           btnSuma.setEnabled(true);
           btnResta.setEnabled(true);
           btnMult.setEnabled(true);
           btnDivision.setEnabled(true);
           btnSuma.setEnabled(true);
           btnResta.setEnabled(true);
           btnMult.setEnabled(true);
           btnDivision.setEnabled(true);
           optSuma.setEnabled(true);
           optResta.setEnabled(true);
           optMult.setEnabled(true);
           optDivision.setEnabled(true);
           btnCalcular.setEnabled(true);
       }else{
           btnSuma.setEnabled(false);
           btnResta.setEnabled(false);
           btnMult.setEnabled(false);
           btnDivision.setEnabled(false);
            btnSuma.setEnabled(false);
           btnResta.setEnabled(false);
           btnMult.setEnabled(false);
           btnDivision.setEnabled(false);
           btnCalcular.setEnabled(false);
           optSuma.setEnabled(false);
           optResta.setEnabled(false);
           optMult.setEnabled(false);
           optDivision.setEnabled(false);
           
       }
       if (key==8){
          c2--;
       } // TODO add your handling code here:
    }//GEN-LAST:event_txt2KeyTyped

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        String txt1,txt2;
        txt1 = this.txt1.getText();   
        txt2 = this.txt2.getText();
        Validaciones v = new Validaciones();
        if(v.validarEnteros(txt1).equals("decimal")){
              //  JOptionPane.showMessageDialog(null, "el numero es un entero");
            float a = Float.parseFloat(txt1);
            if (v.validarEnteros(txt2).equals("decimal")){
                float b = Float.parseFloat(txt2);
                float r = a+b;
                lblresultado.setText(Float.toString(r));
            }else{
                if(v.validarEnteros(txt2).equals("entero")){
                int b = Integer.parseInt(txt2);
                float r = a + b;
                lblresultado.setText(Float.toString(r));
              }
            }
        }else if(v.validarEnteros(txt1).equals("entero")){
            int a = Integer.parseInt(txt1);
            if(v.validarEnteros(txt2).equals("entero")){
                int b = Integer.parseInt(txt2);
                int r = a + b;
                lblresultado.setText(Integer.toString(r));
            }
        }
    }//GEN-LAST:event_btnSumaActionPerformed

    private void btnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaActionPerformed
       
         String txt1,txt2;
        txt1 = this.txt1.getText();   
        txt2 = this.txt2.getText();
        Validaciones v = new Validaciones();
        if(v.validarEnteros(txt1).equals("decimal")){
              //  JOptionPane.showMessageDialog(null, "el numero es un entero");
            float a = Float.parseFloat(txt1);
            if (v.validarEnteros(txt2).equals("decimal")){
                float b = Float.parseFloat(txt2);
                float r = a-b;
                lblresultado.setText(Float.toString(r));
            }else{
                if(v.validarEnteros(txt2).equals("entero")){
                int b = Integer.parseInt(txt2);
                float r = a - b;
                lblresultado.setText(Float.toString(r));
              }
            }
        }else if(v.validarEnteros(txt1).equals("entero")){
            int a = Integer.parseInt(txt1);
            if(v.validarEnteros(txt2).equals("entero")){
                int b = Integer.parseInt(txt2);
                int r = a - b;
                lblresultado.setText(Integer.toString(r));
            }
        }
        

// TODO add your handling code here:
    }//GEN-LAST:event_btnRestaActionPerformed

    private void btnMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultActionPerformed
      
         String txt1,txt2;
        txt1 = this.txt1.getText();   
        txt2 = this.txt2.getText();
        Validaciones v = new Validaciones();
        if(v.validarEnteros(txt1).equals("decimal")){
              //  JOptionPane.showMessageDialog(null, "el numero es un entero");
            float a = Float.parseFloat(txt1);
            if (v.validarEnteros(txt2).equals("decimal")){
                float b = Float.parseFloat(txt2);
                float r = a*b;
                lblresultado.setText(Float.toString(r));
            }else{
                if(v.validarEnteros(txt2).equals("entero")){
                int b = Integer.parseInt(txt2);
                float r = a * b;
                lblresultado.setText(Float.toString(r));
              }
            }
        }else if(v.validarEnteros(txt1).equals("entero")){
            int a = Integer.parseInt(txt1);
            if(v.validarEnteros(txt2).equals("entero")){
                int b = Integer.parseInt(txt2);
                int r = a * b;
                lblresultado.setText(Integer.toString(r));
            }
        }
        



// TODO add your handling code here:
    }//GEN-LAST:event_btnMultActionPerformed

    private void btnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisionActionPerformed
       
         String txt1,txt2;
        txt1 = this.txt1.getText();   
        txt2 = this.txt2.getText();
        Validaciones v = new Validaciones();
        if(v.validarEnteros(txt1).equals("decimal")){
              //  JOptionPane.showMessageDialog(null, "el numero es un entero");
            float a = Float.parseFloat(txt1);
            if (v.validarEnteros(txt2).equals("decimal")){
                float b = Float.parseFloat(txt2);
                float r = a/b;
                lblresultado.setText(Float.toString(r));
            }else{
                if(v.validarEnteros(txt2).equals("entero")){
                float b = Float.parseFloat(txt2);
                float r = a / b;
                lblresultado.setText(Float.toString(r));
              }
            }
        }else if(v.validarEnteros(txt1).equals("entero")){
            float a = Float.parseFloat(txt1);
            if(v.validarEnteros(txt2).equals("entero")){
                float b = Float.parseFloat(txt2);
                float r = a / b;
                lblresultado.setText(Float.toString(r));
            }
        }
        




// TODO add your handling code here:
    }//GEN-LAST:event_btnDivisionActionPerformed

    private void optSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optSumaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optSumaActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed

        String txt1,txt2;
        txt1 = this.txt1.getText();   
        txt2 = this.txt2.getText();
        
        if(optSuma.isSelected()){
            int a = Integer.parseInt(txt1);
            int b = Integer.parseInt(txt2);
            int r = a + b;
            lblresultado.setText(Integer.toString(r));
            
        }
        if(optResta.isSelected()){
            int a = Integer.parseInt(txt1);
            int b = Integer.parseInt(txt2);
            int r = a - b;
            lblresultado.setText(Integer.toString(r));
        }
         if(optMult.isSelected()){
            int a = Integer.parseInt(txt1);
            int b = Integer.parseInt(txt2);
            int r = a * b;
            lblresultado.setText(Integer.toString(r));
        }
          if(optDivision.isSelected()){
            float a = Float.parseFloat(txt1);
            float b = Float.parseFloat(txt2);
            float r = a / b;
            lblresultado.setText(Float.toString(r));
        }
        



// TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void optRestaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_optRestaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_optRestaKeyTyped

    private void btnCalcularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCalcularKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnMult;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnSuma;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblresultado;
    private javax.swing.JRadioButton optDivision;
    private javax.swing.JRadioButton optMult;
    private javax.swing.JRadioButton optResta;
    private javax.swing.JRadioButton optSuma;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    // End of variables declaration//GEN-END:variables
}
